#line 2 "lua_lexxer.cpp"

#line 4 "lua_lexxer.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer lua_lexxer__create_buffer
#define yy_delete_buffer lua_lexxer__delete_buffer
#define yy_flex_debug lua_lexxer__flex_debug
#define yy_init_buffer lua_lexxer__init_buffer
#define yy_flush_buffer lua_lexxer__flush_buffer
#define yy_load_buffer_state lua_lexxer__load_buffer_state
#define yy_switch_to_buffer lua_lexxer__switch_to_buffer
#define yyin lua_lexxer_in
#define yyleng lua_lexxer_leng
#define yylex lua_lexxer_lex
#define yylineno lua_lexxer_lineno
#define yyout lua_lexxer_out
#define yyrestart lua_lexxer_restart
#define yytext lua_lexxer_text
#define yywrap lua_lexxer_wrap
#define yyalloc lua_lexxer_alloc
#define yyrealloc lua_lexxer_realloc
#define yyfree lua_lexxer_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE lua_lexxer_restart(lua_lexxer_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int lua_lexxer_leng;

extern FILE *lua_lexxer_in, *lua_lexxer_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up lua_lexxer_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up lua_lexxer_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via lua_lexxer_restart()), so that the user can continue scanning by
	 * just pointing lua_lexxer_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when lua_lexxer_text is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int lua_lexxer_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow lua_lexxer_wrap()'s to do buffer switches
 * instead of setting up a fresh lua_lexxer_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void lua_lexxer_restart (FILE *input_file  );
void lua_lexxer__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE lua_lexxer__create_buffer (FILE *file,int size  );
void lua_lexxer__delete_buffer (YY_BUFFER_STATE b  );
void lua_lexxer__flush_buffer (YY_BUFFER_STATE b  );
void lua_lexxer_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void lua_lexxer_pop_buffer_state (void );

static void lua_lexxer_ensure_buffer_stack (void );
static void lua_lexxer__load_buffer_state (void );
static void lua_lexxer__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER lua_lexxer__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE lua_lexxer__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE lua_lexxer__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE lua_lexxer__scan_bytes (yyconst char *bytes,int len  );

void *lua_lexxer_alloc (yy_size_t  );
void *lua_lexxer_realloc (void *,yy_size_t  );
void lua_lexxer_free (void *  );

#define yy_new_buffer lua_lexxer__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        lua_lexxer_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            lua_lexxer__create_buffer(lua_lexxer_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        lua_lexxer_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            lua_lexxer__create_buffer(lua_lexxer_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define lua_lexxer_wrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *lua_lexxer_in = (FILE *) 0, *lua_lexxer_out = (FILE *) 0;

typedef int yy_state_type;

extern int lua_lexxer_lineno;

int lua_lexxer_lineno = 1;

extern char *lua_lexxer_text;
#define yytext_ptr lua_lexxer_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up lua_lexxer_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	lua_lexxer_leng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 50
#define YY_END_OF_BUFFER 51
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[156] =
    {   0,
        0,    0,    0,    0,   51,   49,   10,    9,   49,   46,
       49,   46,   46,   40,   40,   47,   46,   46,   46,   49,
       38,   46,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   49,    5,   49,    4,   49,
       49,   10,    0,   43,    0,    0,   44,    0,    8,   32,
       41,   42,   40,    0,    0,   36,   34,   35,    0,   38,
        0,   45,   38,   38,   13,   38,   38,   38,   38,   38,
       20,   21,   38,   38,   38,   25,   38,   38,   38,   38,
       38,   37,    6,    0,    0,    1,    0,   33,    0,   41,
        0,    0,   40,   39,    0,   11,   38,   38,   16,   38,

       18,   38,   38,   23,   24,   38,   38,   38,   38,   38,
       38,    0,    0,    0,    7,    0,   41,    0,    0,   42,
       48,   38,   14,   38,   38,   38,   38,   38,   28,   29,
       38,   38,    0,    0,    0,   41,   12,   38,   17,   38,
       22,   38,   38,   30,   31,    2,    0,   15,   38,   26,
       27,    3,   38,   19,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    1,    6,    1,    7,    6,
        6,    6,    8,    6,    9,   10,    6,   11,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   13,   14,   15,
       16,   17,    1,   18,   19,   19,   19,   19,   20,   19,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   22,   21,   21,
       23,   24,    6,    6,   21,    1,   25,   26,   27,   28,

       29,   30,   21,   31,   32,   21,   33,   34,   35,   36,
       37,   38,   21,   39,   40,   41,   42,   21,   43,   22,
       21,   21,    6,    1,    6,   44,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[45] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        2,    2,    3,    1,    1,    1,    1,    1,    2,    2,
        4,    4,    1,    1,    2,    2,    2,    2,    2,    2,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    1
    } ;

static yyconst flex_int16_t yy_base[162] =
    {   0,
        0,    0,   43,   45,  242,  243,   47,  243,   45,  243,
       49,  232,   50,   54,   74,  243,  224,  223,  222,    0,
        0,   52,  201,  197,  198,   19,   53,   41,  197,   26,
      194,  203,   49,  195,  199,  213,  243,  219,  243,  190,
      184,   85,   77,  243,    0,   84,  243,    0,   74,  215,
       87,   93,   99,  106,    0,  243,  243,  243,  211,    0,
       77,  243,  195,  193,    0,  181,  192,  185,  179,  181,
        0,    0,  189,  181,  173,    0,   82,  184,  170,  170,
      178,  243,  243,  173,  173,  243,  108,  243,  118,  121,
      126,  128,  131,    0,  133,    0,  182,  177,    0,  165,

        0,  177,  178,    0,    0,  173,  159,  164,  170,  166,
      163,  156,  169,  130,  243,  136,  140,  146,  148,  150,
      152,  161,  161,  163,  150,  156,  164,  149,    0,    0,
      152,  154,  115,  120,  154,  156,    0,  106,    0,   93,
        0,   80,   76,    0,    0,  243,   67,    0,   65,    0,
        0,  243,   60,    0,  243,  168,  172,  176,  180,  183,
       65
    } ;

static yyconst flex_int16_t yy_def[162] =
    {   0,
      155,    1,  156,  156,  155,  155,  155,  155,  157,  155,
      158,  155,  155,  155,  155,  155,  155,  155,  155,  159,
      160,  155,  160,  160,  160,  160,  160,  160,  160,  160,
      160,  160,  160,  160,  160,  155,  155,  155,  155,  155,
      155,  155,  157,  155,  157,  158,  155,  158,  155,  155,
      155,  155,  155,  155,  161,  155,  155,  155,  159,  160,
      155,  155,  160,  160,  160,  160,  160,  160,  160,  160,
      160,  160,  160,  160,  160,  160,  160,  160,  160,  160,
      160,  155,  155,  155,  155,  155,  155,  155,  155,  155,
      155,  155,  155,  161,  155,  160,  160,  160,  160,  160,

      160,  160,  160,  160,  160,  160,  160,  160,  160,  160,
      160,  155,  155,  155,  155,  155,  155,  155,  155,  155,
      155,  160,  160,  160,  160,  160,  160,  160,  160,  160,
      160,  160,  155,  155,  155,  155,  160,  160,  160,  160,
      160,  160,  160,  160,  160,  155,  155,  160,  160,  160,
      160,  155,  160,  160,    0,  155,  155,  155,  155,  155,
      155
    } ;

static yyconst flex_int16_t yy_nxt[288] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,   10,   12,   13,
       14,   15,   10,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   22,    6,   23,   24,   21,   25,   26,   27,
       21,   28,   21,   29,   21,   30,   31,   21,   32,   21,
       33,   34,   35,   36,   37,    8,   37,    8,   42,   44,
       42,   38,   66,   38,   67,   47,   39,   74,   39,   50,
       51,   51,   75,   52,   53,   53,   94,   61,   45,   40,
       71,   40,   48,   54,   62,   55,   72,   68,   41,   78,
       41,   44,   54,   52,   53,   53,   42,   79,   42,   69,
       47,   86,   61,   54,   70,  154,   87,   51,   51,   62,

       45,  153,   54,   90,   90,  152,   89,   48,   52,   53,
       53,  151,   91,   92,   92,   89,   93,   93,   54,  106,
      150,   91,  107,  114,  149,  116,  116,   54,  117,  117,
      115,   90,   90,  119,  119,  148,  120,  120,   93,   93,
      118,   93,   93,  121,  121,  114,  117,  117,  147,  118,
      117,  117,  115,  135,  135,  146,  136,  136,  120,  120,
      120,  120,  121,  121,  136,  136,  136,  136,    6,    6,
        6,    6,   43,   43,   43,   43,   46,   46,   46,   46,
       59,   59,  145,   59,   60,  144,   60,  143,  142,  141,
      140,  139,  138,  137,  134,  133,  132,  131,  130,  129,

      128,  127,  126,  125,  124,  123,  122,  113,  112,  111,
      110,  109,  108,  105,  104,  103,  102,  101,  100,   99,
       98,   97,   96,   95,   88,   85,   84,   83,   82,   81,
       80,   77,   76,   73,   65,   64,   63,   58,   57,   56,
       49,  155,    5,  155,  155,  155,  155,  155,  155,  155,
      155,  155,  155,  155,  155,  155,  155,  155,  155,  155,
      155,  155,  155,  155,  155,  155,  155,  155,  155,  155,
      155,  155,  155,  155,  155,  155,  155,  155,  155,  155,
      155,  155,  155,  155,  155,  155,  155
    } ;

static yyconst flex_int16_t yy_chk[288] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    3,    4,    4,    7,    9,
        7,    3,   26,    4,   26,   11,    3,   30,    4,   13,
       13,   13,   30,   14,   14,   14,  161,   22,    9,    3,
       28,    4,   11,   14,   22,   14,   28,   27,    3,   33,
        4,   43,   14,   15,   15,   15,   42,   33,   42,   27,
       46,   49,   61,   15,   27,  153,   49,   51,   51,   61,

       43,  149,   15,   52,   52,  147,   51,   46,   53,   53,
       53,  143,   52,   54,   54,   51,   54,   54,   53,   77,
      142,   52,   77,   87,  140,   89,   89,   53,   89,   89,
       87,   90,   90,   91,   91,  138,   91,   91,   92,   92,
       90,   93,   93,   95,   95,  114,  116,  116,  134,   90,
      117,  117,  114,  118,  118,  133,  118,  118,  119,  119,
      120,  120,  121,  121,  135,  135,  136,  136,  156,  156,
      156,  156,  157,  157,  157,  157,  158,  158,  158,  158,
      159,  159,  132,  159,  160,  131,  160,  128,  127,  126,
      125,  124,  123,  122,  113,  112,  111,  110,  109,  108,

      107,  106,  103,  102,  100,   98,   97,   85,   84,   81,
       80,   79,   78,   75,   74,   73,   70,   69,   68,   67,
       66,   64,   63,   59,   50,   41,   40,   38,   36,   35,
       34,   32,   31,   29,   25,   24,   23,   19,   18,   17,
       12,    5,  155,  155,  155,  155,  155,  155,  155,  155,
      155,  155,  155,  155,  155,  155,  155,  155,  155,  155,
      155,  155,  155,  155,  155,  155,  155,  155,  155,  155,
      155,  155,  155,  155,  155,  155,  155,  155,  155,  155,
      155,  155,  155,  155,  155,  155,  155
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int lua_lexxer__flex_debug;
int lua_lexxer__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *lua_lexxer_text;
#line 1 "lua_lexxer.lex"
#line 2 "lua_lexxer.lex"

/*

Copyright (C) 2008 Google Inc.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE. 

*/

/*

Lua lexxer.

*/

// for win32
#ifdef _MSC_VER
#pragma warning(disable:4018)
#pragma warning(disable:4102)
#pragma warning(disable:4244)
#pragma warning(disable:4267)
#pragma warning(disable:4996)
#pragma warning(disable:4003)

#include <io.h>
#include <stdio.h>
#endif

// Semantic values.
#define YYSTYPE char*

#ifndef _MSC_VER
#include <libgen.h>			// For dirname()
#else

#include <stdio.h>
#include <conio.h>
#include <stdlib.h>
#include <direct.h>

static const char *dirname(const char *partialPath)
{
	static char full[1000] = {0};
	static char path_buffer[1000] = {0};
	static char drive[1000] = {0};
	static char dir[1000] = {0};
	static char fname[1000] = {0};
	static char ext[1000] = {0};
	static char fulldir[1000] = {0};
	if( _fullpath( full, partialPath, sizeof(full) ) != NULL )
	{
		_splitpath( full, drive, dir, fname, ext );
		strcpy(fulldir, drive);
		strcat(fulldir, dir);
	}
	else
	{
		strcpy(fulldir, "");
	}
   	return fulldir;
}
#endif


#include <vector>
#include <string>
#include "util.h"
#include "lua_parser.h"

// Constants.
#define MAX_INCLUDE_DEPTH 100

// Information about the main file and files nested with 'dofile'.
struct FileInfo {
  YY_BUFFER_STATE buffer;
  char *filename;			// Name of file being processed
  int line_count;			// Current line position in file
  int marker_line_number;		// Last @filename:number line number
  const char *marker_filename;		// Last @filename:number filename

  FileInfo() { memset(this, 0, sizeof(*this)); }
};

// Local state.
static std::vector<FileInfo> files;	// Top level and nested files
static bool expand_special_tokens;      // Controls production of SPECIAL tokens
static bool ignore_first_semicolon;	// Ignore ';' one time

// Return a token number to the caller and set the location.
#define TOKEN(n) { int ret = n; SetLocation(yylloc); ignore_first_semicolon = false; return ret; }

// Set location information for a token.
static void SetLocation(YYLTYPE *yylloc) {
  yylloc->line = files.back().marker_line_number ?
    files.back().marker_line_number : files.back().line_count;
  yylloc->filename = files.back().marker_line_number ?
    files.back().marker_filename : files.back().filename;
}

// Return the number of characters 'c' in the given string.
static int CountChars(const char *s, char c) {
  int count = 0;
  while (*s) {
    if (*s == c) count++;
    s++;
  }
  return count;
}

// Complain about a bad character in the input.
static void PanicWithBadChar(int c) {
  if (c >= 32 && c <= 126) {
    Panic("Unexpected character '%c', at %s:%d", c,
          files.back().filename, files.back().line_count);
  } else {
    Panic("Unexpected character #%d, at %s:%d", (unsigned char) c,
          files.back().filename, files.back().line_count);
  }
}

// Skip over '#!...' on the first line of a file, return true if a line was
// skipped.
static bool SkipInterpreterLine(FILE *fin) {
  int c = fgetc(fin);
  if (c == '#') {
    for(;;) {
      c = fgetc(fin);
      if (c == '\n' || c == EOF) break;
    }
    return true;
  } else {
    ungetc(c, fin);
    return false;
  }
}

void InitializeLexxer(const char *filename, bool _expand_special_tokens) {
#ifndef _MSC_VER
  if (strchr(filename, ':')) Panic("Colons not allowed in filenames (%s)", filename);
#endif
  lua_lexxer_in = fopen(filename,"rb");
  if (!lua_lexxer_in) Panic("Can not open %s (%s)", filename, strerror(errno));

  FileInfo file;
  file.filename = strdup(filename);
  file.line_count = 1 + SkipInterpreterLine(lua_lexxer_in);
  file.marker_line_number = 0;
  file.marker_filename = 0;
  files.push_back(file);

  expand_special_tokens = _expand_special_tokens;
  ignore_first_semicolon = false;
}

void FinalizeLexxer() {
  fclose(lua_lexxer_in);
}

void LexxerPushFile(const char *filename) {
  if (files.size() >= MAX_INCLUDE_DEPTH) {
    Panic("dofile() files nested too deeply, at %s:%d",
          files.back().filename, files.back().line_count);
  }
  files.back().buffer = YY_CURRENT_BUFFER;
  std::string fname = dirname(strdup(files[0].filename));
  fname += "/";
  fname += filename + 1;		// Chop off first quote
  fname.resize(fname.size() - 1);	// Chop off last quote
  InitializeLexxer(fname.c_str(), expand_special_tokens);
  lua_lexxer__switch_to_buffer(lua_lexxer__create_buffer(lua_lexxer_in,YY_BUF_SIZE));	//@@@ can we not use the global lua_lexxer_in?
}

const char *LexxerFilename() {
  return files.back().filename;
}

int LexxerLinecount() {
  return files.back().line_count;
}

// Forward declarations.
static void SingleLineComment(char **ret_string);
static void MultilineCommentOrString(char *prefix, char **ret_string);
static bool HandleEndOfFile();

//%option outfile="lex.yy.c"

#define YY_NO_UNISTD_H 1
#line 791 "lua_lexxer.cpp"

#define INITIAL 0
#define special 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int lua_lexxer_lex_destroy (void );

int lua_lexxer_get_debug (void );

void lua_lexxer_set_debug (int debug_flag  );

YY_EXTRA_TYPE lua_lexxer_get_extra (void );

void lua_lexxer_set_extra (YY_EXTRA_TYPE user_defined  );

FILE *lua_lexxer_get_in (void );

void lua_lexxer_set_in  (FILE * in_str  );

FILE *lua_lexxer_get_out (void );

void lua_lexxer_set_out  (FILE * out_str  );

int lua_lexxer_get_leng (void );

char *lua_lexxer_get_text (void );

int lua_lexxer_get_lineno (void );

void lua_lexxer_set_lineno (int line_number  );

YYSTYPE * lua_lexxer_get_lval (void );

void lua_lexxer_set_lval (YYSTYPE * yylval_param  );

       YYLTYPE *lua_lexxer_get_lloc (void );
    
        void lua_lexxer_set_lloc (YYLTYPE * yylloc_param  );
    
/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int lua_lexxer_wrap (void );
#else
extern int lua_lexxer_wrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( lua_lexxer_text, lua_lexxer_leng, 1, lua_lexxer_out )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( lua_lexxer_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( lua_lexxer_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, lua_lexxer_in))==0 && ferror(lua_lexxer_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(lua_lexxer_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int lua_lexxer_lex \
               (YYSTYPE * yylval_param,YYLTYPE * yylloc_param );

#define YY_DECL int lua_lexxer_lex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param )
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after lua_lexxer_text and lua_lexxer_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
        YYSTYPE * yylval;
    
        YYLTYPE * yylloc;
    
#line 213 "lua_lexxer.lex"


#line 991 "lua_lexxer.cpp"

    yylval = yylval_param;

    yylloc = yylloc_param;

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! lua_lexxer_in )
			lua_lexxer_in = stdin;

		if ( ! lua_lexxer_out )
			lua_lexxer_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			lua_lexxer_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				lua_lexxer__create_buffer(lua_lexxer_in,YY_BUF_SIZE );
		}

		lua_lexxer__load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of lua_lexxer_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 156 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 243 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 215 "lua_lexxer.lex"
{
					  if (expand_special_tokens) {
					    BEGIN(special);
					  } else {
					    SingleLineComment(yylval);
					    TOKEN(SPECIAL);
					  }
					}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 223 "lua_lexxer.lex"
{ TOKEN(SPECIAL_CONST); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 224 "lua_lexxer.lex"
{ TOKEN(SPECIAL_NUMBER); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 225 "lua_lexxer.lex"
{ TOKEN(';'); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 226 "lua_lexxer.lex"
{ /* Ignore whitespace in one line */ }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 227 "lua_lexxer.lex"
{ SingleLineComment(0); BEGIN(INITIAL); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 229 "lua_lexxer.lex"
{ MultilineCommentOrString(lua_lexxer_text, 0); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 230 "lua_lexxer.lex"
{ SingleLineComment(0); }
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 231 "lua_lexxer.lex"
{ files.back().line_count++; BEGIN(INITIAL); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 232 "lua_lexxer.lex"
{ /* Ignore whitespace */ }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 234 "lua_lexxer.lex"
{ TOKEN(AND); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 235 "lua_lexxer.lex"
{ TOKEN(BREAK); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 236 "lua_lexxer.lex"
{ TOKEN(DO); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 237 "lua_lexxer.lex"
{ TOKEN(ELSE); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 238 "lua_lexxer.lex"
{ TOKEN(ELSEIF); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 239 "lua_lexxer.lex"
{ TOKEN(END); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 240 "lua_lexxer.lex"
{ TOKEN(FALSE); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 241 "lua_lexxer.lex"
{ TOKEN(FOR); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 242 "lua_lexxer.lex"
{ TOKEN(FUNCTION); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 243 "lua_lexxer.lex"
{ TOKEN(IF); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 244 "lua_lexxer.lex"
{ TOKEN(IN); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 245 "lua_lexxer.lex"
{ TOKEN(LOCAL); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 246 "lua_lexxer.lex"
{ TOKEN(NIL); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 247 "lua_lexxer.lex"
{ TOKEN(NOT); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 248 "lua_lexxer.lex"
{ TOKEN(OR); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 249 "lua_lexxer.lex"
{ TOKEN(REPEAT); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 250 "lua_lexxer.lex"
{ TOKEN(RETURN); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 251 "lua_lexxer.lex"
{ TOKEN(THEN); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 252 "lua_lexxer.lex"
{ TOKEN(TRUE); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 253 "lua_lexxer.lex"
{ TOKEN(UNTIL); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 254 "lua_lexxer.lex"
{ TOKEN(WHILE); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 255 "lua_lexxer.lex"
{ TOKEN(CONCAT); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 256 "lua_lexxer.lex"
{ TOKEN(ELLIPSES); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 257 "lua_lexxer.lex"
{ TOKEN(EQ); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 258 "lua_lexxer.lex"
{ TOKEN(GE); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 259 "lua_lexxer.lex"
{ TOKEN(LE); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 260 "lua_lexxer.lex"
{ TOKEN(NE); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 262 "lua_lexxer.lex"
{ *yylval = strdup(lua_lexxer_text); TOKEN(IDENTIFIER); }
	YY_BREAK
case 39:
#line 265 "lua_lexxer.lex"
case 40:
#line 266 "lua_lexxer.lex"
case 41:
#line 267 "lua_lexxer.lex"
case 42:
YY_RULE_SETUP
#line 267 "lua_lexxer.lex"
{ *yylval = strdup(lua_lexxer_text); TOKEN(NUMBER); }
	YY_BREAK
case 43:
/* rule 43 can match eol */
#line 270 "lua_lexxer.lex"
case 44:
/* rule 44 can match eol */
YY_RULE_SETUP
#line 270 "lua_lexxer.lex"
{ *yylval = strdup(lua_lexxer_text); TOKEN(STRING); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 271 "lua_lexxer.lex"
{ MultilineCommentOrString(lua_lexxer_text, yylval); TOKEN(STRING); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 273 "lua_lexxer.lex"
{ TOKEN(lua_lexxer_text[0]); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 275 "lua_lexxer.lex"
{
					  if (ignore_first_semicolon) {
					    ignore_first_semicolon = false;
					  } else {
					    TOKEN(';');
					  }
					}
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 283 "lua_lexxer.lex"
{
					  // A special filename:line_number marker that is not part
					  // of regular Lua syntax.
					  char *colon = strchr(lua_lexxer_text, ':');
					  *colon = 0;
					  files.back().marker_filename = strdup(lua_lexxer_text + 1);
					  files.back().marker_line_number = atoi(colon + 1);
					}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 292 "lua_lexxer.lex"
{ PanicWithBadChar(lua_lexxer_text[0]); }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(special):
#line 294 "lua_lexxer.lex"
{ if (HandleEndOfFile()) return 0; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 296 "lua_lexxer.lex"
ECHO;
	YY_BREAK
#line 1345 "lua_lexxer.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed lua_lexxer_in at a new source and called
			 * lua_lexxer_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = lua_lexxer_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( lua_lexxer_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * lua_lexxer_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of lua_lexxer_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					lua_lexxer_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			lua_lexxer_restart(lua_lexxer_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) lua_lexxer_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 156 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 156 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 155);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up lua_lexxer_text */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					lua_lexxer_restart(lua_lexxer_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( lua_lexxer_wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve lua_lexxer_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void lua_lexxer_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        lua_lexxer_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            lua_lexxer__create_buffer(lua_lexxer_in,YY_BUF_SIZE );
	}

	lua_lexxer__init_buffer(YY_CURRENT_BUFFER,input_file );
	lua_lexxer__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void lua_lexxer__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		lua_lexxer_pop_buffer_state();
	 *		lua_lexxer_push_buffer_state(new_buffer);
     */
	lua_lexxer_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	lua_lexxer__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (lua_lexxer_wrap()) processing, but the only time this flag
	 * is looked at is after lua_lexxer_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void lua_lexxer__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	lua_lexxer_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE lua_lexxer__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) lua_lexxer_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in lua_lexxer__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) lua_lexxer_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in lua_lexxer__create_buffer()" );

	b->yy_is_our_buffer = 1;

	lua_lexxer__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with lua_lexxer__create_buffer()
 * 
 */
    void lua_lexxer__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		lua_lexxer_free((void *) b->yy_ch_buf  );

	lua_lexxer_free((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a lua_lexxer_restart() or at EOF.
 */
    static void lua_lexxer__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	lua_lexxer__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then lua_lexxer__init_buffer was _probably_
     * called from lua_lexxer_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void lua_lexxer__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		lua_lexxer__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void lua_lexxer_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	lua_lexxer_ensure_buffer_stack();

	/* This block is copied from lua_lexxer__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from lua_lexxer__switch_to_buffer. */
	lua_lexxer__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void lua_lexxer_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	lua_lexxer__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		lua_lexxer__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void lua_lexxer_ensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)lua_lexxer_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in lua_lexxer_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)lua_lexxer_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in lua_lexxer_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE lua_lexxer__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) lua_lexxer_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in lua_lexxer__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	lua_lexxer__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to lua_lexxer_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       lua_lexxer__scan_bytes() instead.
 */
YY_BUFFER_STATE lua_lexxer__scan_string (yyconst char * yystr )
{
    
	return lua_lexxer__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to lua_lexxer_lex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE lua_lexxer__scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) lua_lexxer_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in lua_lexxer__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = lua_lexxer__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in lua_lexxer__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up lua_lexxer_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		lua_lexxer_text[lua_lexxer_leng] = (yy_hold_char); \
		(yy_c_buf_p) = lua_lexxer_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		lua_lexxer_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int lua_lexxer_get_lineno  (void)
{
        
    return lua_lexxer_lineno;
}

/** Get the input stream.
 * 
 */
FILE *lua_lexxer_get_in  (void)
{
        return lua_lexxer_in;
}

/** Get the output stream.
 * 
 */
FILE *lua_lexxer_get_out  (void)
{
        return lua_lexxer_out;
}

/** Get the length of the current token.
 * 
 */
int lua_lexxer_get_leng  (void)
{
        return lua_lexxer_leng;
}

/** Get the current token.
 * 
 */

char *lua_lexxer_get_text  (void)
{
        return lua_lexxer_text;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void lua_lexxer_set_lineno (int  line_number )
{
    
    lua_lexxer_lineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see lua_lexxer__switch_to_buffer
 */
void lua_lexxer_set_in (FILE *  in_str )
{
        lua_lexxer_in = in_str ;
}

void lua_lexxer_set_out (FILE *  out_str )
{
        lua_lexxer_out = out_str ;
}

int lua_lexxer_get_debug  (void)
{
        return lua_lexxer__flex_debug;
}

void lua_lexxer_set_debug (int  bdebug )
{
        lua_lexxer__flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from lua_lexxer_lex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    lua_lexxer_in = stdin;
    lua_lexxer_out = stdout;
#else
    lua_lexxer_in = (FILE *) 0;
    lua_lexxer_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * lua_lexxer_lex_init()
     */
    return 0;
}

/* lua_lexxer_lex_destroy is for both reentrant and non-reentrant scanners. */
int lua_lexxer_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		lua_lexxer__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		lua_lexxer_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	lua_lexxer_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * lua_lexxer_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *lua_lexxer_alloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *lua_lexxer_realloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void lua_lexxer_free (void * ptr )
{
	free( (char *) ptr );	/* see lua_lexxer_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 296 "lua_lexxer.lex"



// These functions are defined down here because they need to call yyinput() or
// other lexxer functions.

// Skip a single line comment in the lexxer input file. If ret_string is
// nonzero then save the comment line in the string.
static void SingleLineComment(char **ret_string) {
  std::string buffer;
  if (ret_string) buffer += " --@";
  for(;;) {
    int c = yyinput();
    if (c == '\n') {
      files.back().line_count++;
    } else if (ret_string) {
#if defined(_MSC_VER) && _MSC_VER <= 1200
	  buffer.append(1, c); 
#else
      buffer.push_back(c);
#endif
    }
    if (c == '\n' || c == EOF) {
      if (ret_string) {
        *ret_string = strdup(buffer.c_str());
      }
      return;
    }
  }
}

// This scans the lexxer input file until it finds ]===] where the number of '='
// characters to match is the number present in the prefix. If ret_string is
// nonzero then it is set to a string containing the prefix plus the scanned
// characters.
static void MultilineCommentOrString(char *prefix, char **ret_string) {
  int equals_to_match = CountChars(prefix, '=');
  int startline = files.back().line_count;
  int state = 0;
  std::string buffer;
  if (ret_string) buffer += prefix;
  for (;;) {
    int c = yyinput();
#if defined(_MSC_VER) && _MSC_VER <= 1200
    if (ret_string) buffer.append(1, c);
#else
    if (ret_string) buffer.push_back(c);
#endif
    if (c == EOF) {
      files.back().line_count = startline;
      Panic("Unclosed long comment or string, at %s:%d",
            files.back().filename, files.back().line_count);
    }
    if (c == '\n') files.back().line_count++;

    if (state == equals_to_match+1) {
      if (c == ']') {
        if (ret_string) {
          CHECK(int(buffer.length()) >= equals_to_match+2);
          *ret_string = strdup(buffer.c_str());
        }
        return;
      }
      state = 0;
    } else if (state == 0) {
      if (c == ']') state = 1;
    } else {
      if (c == '=') state++;
      else if (c == ']') state = 1;
      else state = 0;
    }
  }
}

static bool HandleEndOfFile() {
  if (files.size() <= 1) {	
    return true;
  } else {
    files.pop_back();
    lua_lexxer__delete_buffer(YY_CURRENT_BUFFER);
    lua_lexxer__switch_to_buffer(files.back().buffer);

    // The expanded "dofile 'filename'" statement might be followed by a
    // semicolon. If we see it, ignore it, since it wont be syntactically
    // valid after the expanded code.
    ignore_first_semicolon = true;

    return false;
  }
}

